### Endpoint test
GET http://localhost:3003/ping

### Signup 
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Gal Costa",
    "email": "galcosta@gmail.com",
    "password": "babybabyuh"
}

### Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "bethania@gmail.com",
    "password": "abelharainha13"
}

### Create new post
POST http://localhost:3003/posts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ0YzkyYWZiLWQzMWItNDQ0OC1iOTk0LTljYzMxNWUyOGUyMiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjAxNjMzODAsImV4cCI6MTY2MDI0OTc4MH0.dsAffsZoE7Xa24MuyiWDPx2niBKWdHHjR54n8pcFZ2U
Content-Type: application/json

{
    "text": "Nova turnê em breve!"
}

### Get all posts
GET http://localhost:3003/posts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ0YzkyYWZiLWQzMWItNDQ0OC1iOTk0LTljYzMxNWUyOGUyMiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjAxNjMzODAsImV4cCI6MTY2MDI0OTc4MH0.dsAffsZoE7Xa24MuyiWDPx2niBKWdHHjR54n8pcFZ2U

### Delete post
DELETE http://localhost:3003/posts/af619f96-c19b-466a-b427-1ddd6eb94d9f
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ0YzkyYWZiLWQzMWItNDQ0OC1iOTk0LTljYzMxNWUyOGUyMiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjAxNjMzODAsImV4cCI6MTY2MDI0OTc4MH0.dsAffsZoE7Xa24MuyiWDPx2niBKWdHHjR54n8pcFZ2U

### Like post
POST http://localhost:3003/posts/101
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUwNWFjYmYyLWVlZDQtNDVhMS05NmJmLWYxMmUxY2Q1ODNkMyIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjAyNDAzMjgsImV4cCI6MTY2MDMyNjcyOH0.ORFA5zXHbhDI2TttXsPe1EugFcZG2E6OssJJKKhw3-4

